//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbaranesClientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlbaranesClientes()
        {
            this.AlbaranesClienteDetalles = new HashSet<AlbaranesClienteDetalles>();
            this.AlbaranesClientesBases = new HashSet<AlbaranesClientesBases>();
        }
    
        public decimal AlbaranId { get; set; }
        public decimal EmpresaId { get; set; }
        public decimal ClienteId { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Facturado { get; set; }
        public Nullable<decimal> FacturaId { get; set; }
        public Nullable<bool> AlbaranesRecargo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbaranesClienteDetalles> AlbaranesClienteDetalles { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Empresas Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbaranesClientesBases> AlbaranesClientesBases { get; set; }
    }
}
