//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturas()
        {
            this.FacturasBases = new HashSet<FacturasBases>();
            this.FacturasDetalles = new HashSet<FacturasDetalles>();
            this.Recibos = new HashSet<Recibos>();
            this.FacturasDetallesLotes = new HashSet<FacturasDetallesLotes>();
        }
    
        public decimal FacturaId { get; set; }
        public decimal EmpresaId { get; set; }
        public decimal ClienteId { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Impreso { get; set; }
        public decimal FormaPagoId { get; set; }
        public Nullable<bool> FacturaRecargo { get; set; }
        public Nullable<decimal> PresupuestoId { get; set; }
        public bool Finalizado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empresas Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasBases> FacturasBases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasDetalles> FacturasDetalles { get; set; }
        public virtual FormasPagos FormasPagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recibos> Recibos { get; set; }
        public virtual Presupuestos Presupuestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasDetallesLotes> FacturasDetallesLotes { get; set; }
    }
}
