//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosInventario
    {
        public decimal MovimientoId { get; set; }
        public decimal EmpresaId { get; set; }
        public decimal ArticuloId { get; set; }
        public decimal LoteArticuloId { get; set; }
        public decimal Cantidad { get; set; }
        public string TipoMovimiento { get; set; }
        public decimal CantidadAntes { get; set; }
        public decimal CantidadDespues { get; set; }
        public decimal DocumentoRelacionado { get; set; }
        public string TipoDocumentoRelacionado { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual Empresas Empresas { get; set; }
    }
}
