//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibos
    {
        public decimal ReciboId { get; set; }
        public decimal PlazoId { get; set; }
        public decimal FacturaId { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Importe { get; set; }
        public bool Cobrado { get; set; }
    
        public virtual Facturas Facturas { get; set; }
    }
}
