//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ArticulosConsulta
    {
        public decimal ArticuloId { get; set; }
        public string Referencia { get; set; }
        public decimal EmpresaId { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
    }
}
